# Generated by Django 4.2.3 on 2023-07-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='types',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
