# Generated by Django 4.2.3 on 2023-08-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(default='Unassigned', max_length=25)),
                ('company_details', models.TextField(null=True)),
                ('project_details', models.TextField(null=True)),
                ('contact_details', models.TextField(null=True)),
                ('information', models.TextField(null=True)),
                ('agent', models.OneToOneField(limit_choices_to={'groups__name': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_opportunity', to=settings.AUTH_USER_MODEL)),
                ('manager', models.OneToOneField(limit_choices_to={'groups__name': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_opportunity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunities',
            },
        ),
        migrations.CreateModel(
            name='OpportunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(null=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunity_comment', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_opportunity_comment', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.opportunity')),
            ],
            options={
                'db_table': 'opportunity_comments',
            },
        ),
    ]
