# Generated by Django 4.2.3 on 2024-08-29 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(default='Unassigned', max_length=25)),
                ('company_name', models.TextField(null=True)),
                ('company_details', models.TextField(null=True)),
                ('opportunity_details', models.TextField(null=True)),
                ('contact_details', models.TextField(null=True)),
                ('additional_info', models.TextField(null=True)),
                ('agent', models.ForeignKey(limit_choices_to={'groups__name': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_opportunity', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'groups__name': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_opportunity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunities',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Key_note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_proposal', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_proposal', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.opportunity')),
            ],
            options={
                'db_table': 'proposals',
            },
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='project_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposal_cby', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_docs', to='deal.proposal')),
            ],
            options={
                'db_table': 'proposal_documents',
            },
        ),
        migrations.CreateModel(
            name='OpportunityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='project_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents_cby', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_docs', to='deal.opportunity')),
            ],
            options={
                'db_table': 'opportunity_documents',
            },
        ),
        migrations.CreateModel(
            name='OpportunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunity_comment', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_opportunity_comment', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.opportunity')),
            ],
            options={
                'db_table': 'opportunity_comments',
            },
        ),
    ]
