# Generated by Django 4.2.3 on 2023-08-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='information',
            new_name='additional_info',
        ),
        migrations.AddField(
            model_name='opportunitycomment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_opportunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_opportunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OpportunityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='project_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_docs', to='deal.opportunity')),
            ],
            options={
                'db_table': 'opportunity_documents',
            },
        ),
    ]
