# Generated by Django 4.2.3 on 2023-08-20 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0002_opportunitycomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_opportunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_opportunity', to=settings.AUTH_USER_MODEL),
        ),
    ]
