# Generated by Django 4.2.3 on 2023-08-27 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0002_rename_information_opportunity_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitydocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
