# Generated by Django 4.2.3 on 2024-08-31 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_proposalversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='proposal_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pv_docs', to='deal.proposal'),
            preserve_default=False,
        ),
    ]
