# Generated by Django 4.2.3 on 2023-09-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_alter_opportunitydocument_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
