# Generated by Django 4.2.3 on 2024-10-02 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0003_proposaldocument_proposal_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'agent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_opportunity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'manager'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_opportunity', to=settings.AUTH_USER_MODEL),
        ),
    ]
