# Generated by Django 4.2.3 on 2024-10-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_alter_opportunity_agent_alter_opportunity_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalversion',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
