# Generated by Django 4.2.3 on 2023-08-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_document_opportunity_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='information',
            new_name='additional_info',
        ),
    ]
