# Generated by Django 4.2.3 on 2024-10-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_proposalversion_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaldocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='proposaldocument',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposaldocument',
            name='proposal_version',
        ),
        migrations.RemoveField(
            model_name='proposalversion',
            name='proposal',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='ProposalDocument',
        ),
    ]
