# Generated by Django 4.2.3 on 2024-10-19 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0006_remove_proposaldocument_created_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProposalVersion',
            new_name='Proposal',
        ),
        migrations.AlterModelTable(
            name='proposal',
            table='proposals',
        ),
    ]
