# Generated by Django 4.2.3 on 2023-12-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_opportunity_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='project_details',
            new_name='opportunity_details',
        ),
    ]
