# Generated by Django 4.2.3 on 2024-10-19 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deal', '0007_rename_proposalversion_proposal_alter_proposal_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='project_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposal_cby', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_docs', to='deal.proposal')),
                ('proposal_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pv_docs', to='deal.proposal')),
            ],
            options={
                'db_table': 'proposal_documents',
            },
        ),
    ]
