# Generated by Django 4.2.3 on 2024-10-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_proposaldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaldocument',
            name='proposal_version',
        ),
    ]
