# Generated by Django 4.2.3 on 2024-10-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_remove_proposaldocument_proposal_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.opportunity'),
        ),
    ]
