# Generated by Django 4.2.3 on 2024-07-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_proposal_remarks_proposal_result_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proposal',
            table='proposals',
        ),
    ]
