# Generated by Django 4.2.3 on 2024-11-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0010_alter_proposal_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='modified_by',
        ),
    ]
