# Generated by Django 4.2.3 on 2024-11-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0012_proposal_created_at_proposal_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.opportunity', to_field='uuid'),
        ),
    ]
